# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services.definitions import car_sale_pb2 as services_dot_definitions_dot_car__sale__pb2


class CarSaleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAdsList = channel.unary_unary(
                '/CarSale/GetAdsList',
                request_serializer=services_dot_definitions_dot_car__sale__pb2.AdsListRequest.SerializeToString,
                response_deserializer=services_dot_definitions_dot_car__sale__pb2.AdsListResponse.FromString,
                )
        self.AddOffer = channel.unary_unary(
                '/CarSale/AddOffer',
                request_serializer=services_dot_definitions_dot_car__sale__pb2.AddOfferRequest.SerializeToString,
                response_deserializer=services_dot_definitions_dot_car__sale__pb2.AddOfferResponse.FromString,
                )
        self.AddAdvertisement = channel.unary_unary(
                '/CarSale/AddAdvertisement',
                request_serializer=services_dot_definitions_dot_car__sale__pb2.AddAdvertisementRequest.SerializeToString,
                response_deserializer=services_dot_definitions_dot_car__sale__pb2.AddAdvertisementResponse.FromString,
                )


class CarSaleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAdsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAdvertisement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarSaleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAdsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdsList,
                    request_deserializer=services_dot_definitions_dot_car__sale__pb2.AdsListRequest.FromString,
                    response_serializer=services_dot_definitions_dot_car__sale__pb2.AdsListResponse.SerializeToString,
            ),
            'AddOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOffer,
                    request_deserializer=services_dot_definitions_dot_car__sale__pb2.AddOfferRequest.FromString,
                    response_serializer=services_dot_definitions_dot_car__sale__pb2.AddOfferResponse.SerializeToString,
            ),
            'AddAdvertisement': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAdvertisement,
                    request_deserializer=services_dot_definitions_dot_car__sale__pb2.AddAdvertisementRequest.FromString,
                    response_serializer=services_dot_definitions_dot_car__sale__pb2.AddAdvertisementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CarSale', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CarSale(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAdsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CarSale/GetAdsList',
            services_dot_definitions_dot_car__sale__pb2.AdsListRequest.SerializeToString,
            services_dot_definitions_dot_car__sale__pb2.AdsListResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CarSale/AddOffer',
            services_dot_definitions_dot_car__sale__pb2.AddOfferRequest.SerializeToString,
            services_dot_definitions_dot_car__sale__pb2.AddOfferResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddAdvertisement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CarSale/AddAdvertisement',
            services_dot_definitions_dot_car__sale__pb2.AddAdvertisementRequest.SerializeToString,
            services_dot_definitions_dot_car__sale__pb2.AddAdvertisementResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
